version: "3"

vars:
  BUILDER_IMAGE_TAG: anyboards-protoc:latest
  BUILD_VOLUME: /build

tasks:
  gen:
    cmds:
      - task: builder

      - rm -rf gen

      - task: protoc
        vars: { PROTO_FILE: proto/debug.proto, OUT_DIR: debug }

      #- task: protoc
      #  vars: { PROTO_FILE: proto/boards.proto, OUT_DIR: boards }

      - task: godeps

  builder:
    internal: true
    cmds:
      - docker build -t {{.BUILDER_IMAGE_TAG}} .

  protoc:
    internal: true
    vars:
      GO_OUT_DIR: "{{.BUILD_VOLUME}}/gen/go/{{.OUT_DIR}}"
      JS_OUT_DIR: "{{.BUILD_VOLUME}}/gen/js/{{.OUT_DIR}}"
    cmds:
      - mkdir -p gen/go/{{.OUT_DIR}}
      - mkdir -p gen/js/{{.OUT_DIR}}
      - >-
        docker run --rm -i -v=.:{{.BUILD_VOLUME}} {{.BUILDER_IMAGE_TAG}}
        protoc --proto_path={{.BUILD_VOLUME}}/proto {{.BUILD_VOLUME}}/{{.PROTO_FILE}}
        --go_out={{.GO_OUT_DIR}} --go_opt=paths=source_relative
        --go-grpc_out={{.GO_OUT_DIR}} --go-grpc_opt=paths=source_relative
        --js_out=import_style=commonjs:{{.JS_OUT_DIR}}
        --grpc-web_out=import_style=typescript,mode=grpcwebtext:{{.JS_OUT_DIR}}

  godeps:
    internal: true
    cmd: >-
      docker run --rm -i -v=.:{{.BUILD_VOLUME}} {{.BUILDER_IMAGE_TAG}}
      /bin/sh -c cd {{.BUILD_VOLUME}} && go mod tidy && go get -u ./...

