################################################
### !!! This file is for testing purpose !!! ###
################################################
version: "3"

tasks:
  protoc:
    desc: "Generate code from proto files"
    vars:
      PROTO_FILES:
        # Find all proto files in the current directory and cut extensions
        sh: find . -maxdepth 1 -type file -name '*.proto' | xargs -I{} basename {} '.proto'
    cmds:
      - for: { var: PROTO_FILES }
        cmd: >-
          mkdir -p {{.ITEM}} &&
          protoc --proto_path=. {{.ITEM}}.proto
          --go_out={{.ITEM}} --go_opt=paths=source_relative
          --go-grpc_out={{.ITEM}} --go-grpc_opt=paths=source_relative
